### ISSUE TITLE
add snapshots test back to `parser`

### ISSUE THREAD

**Issue by psteinroe** [supabase/postgres_lsp#82]
## Planned Work

We already had it in place but dropped it because it's unnecessary now that the parser panics on invalid statements. but turns out it's actually quite useful when reviewing pull requests for #51. we should add it back using [`insta`](https://docs.rs/insta/latest/insta/) as before. we should be able to simply copy it from the git history of the `statement_parser_test` file.

**Comment by cvng** [comment]
Yeah, I was exactly thinking about this, having `insta` back will help making PRs related to #51 less tedious

**Comment by psteinroe** [comment]
> Another great addition could be testing against postgres [regression tests](https://github.com/postgres/postgres/tree/master/src/test/regress/sql) as well

ohh thats a great idea! we can just copy the sql files, or add the entire postgres repo as a submodule to keep it up-to-date. wdyt?

**Comment by cvng** [comment]
I was planning at first to pull the sql files with a tiny script and later add it as a submodule when progress has been made

**Comment by psteinroe** [comment]
@cvng can you open a separate issue for pulling in the regression tests?

**Comment by cvng** [comment]
@psteinroe sure, I already had a few PRs stacked for #51, so I will proceed to pull the postgres tests once those are merged

**Comment by psteinroe** [comment]
> EDIT: also, should we somehow consolidate parser e2e & unit tests? eg. add get_node_properties in the snapshots

the `get_node_properties` tests should rather serve as a help for devs to figure out the right props fast - I would keep them separated.
