### ISSUE TITLE
[Bug] Initial build for development is failing

### ISSUE THREAD

**Issue by mobley-trent** [supabase/postgres_lsp#96]
# Bug report

- [ ] I confirm this is a bug with Supabase, not with my own application.
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com).

## Describe the bug

I can't build the project hence I can't start developing. I tried running `git submodule update --init --recursive`, but I'm getting this error:
```
fatal: Unable to find current revision in submodule path 'libpg_query'
```
I can't seem to pull the `libpg_query` submodule

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the repo
2. Run `git submodule update --init --recursive` on the shell.
3. See error

## Expected behavior

I expect the submodule to be pulled so that the build process can continue.

## Screenshots

![Screenshot 2023-12-25 120506](https://github.com/supabase/postgres_lsp/assets/67474838/8edaf65d-4775-4b8a-8615-f11fa5f0a5bd)
![Screenshot 2023-12-25 120533](https://github.com/supabase/postgres_lsp/assets/67474838/8e6a0302-c637-4a75-a586-2b7745e6f717)

## System information

- OS: Windows 10

**Comment by psteinroe** [comment]
hey @mobley-trent, thanks for your effort!

Unfortunately, libpg_query is not supported on windows, so you will have to setup a remote machine to start developing. I didn't have the time to write up a guide for this, maybe you can support?

**Comment by mobley-trent** [comment]
Sure @psteinroe 
Do you mean making changes to the docs in regard to support on Windows ?

**Comment by psteinroe** [comment]
@mobley-trent yes, maybe add a note about missing window support with a link to the issue in libpg_query. And if you are experienced with it, maybe try to setup a dev environment with code spaces or docker or similar and write a guide for others. That would be awesome!
